### ISSUE TITLE
Schriftgröße headline About und Impressum

### ISSUE THREAD

**Issue by lushsounds** [blogbasti/klangturm#27]
Hi Sebastian, 
könntest Du bitte die schriftgröße der Überschriften bei about und Impressum genau so machen wie bei den Überschriften der Künstlerseiten?
Danke und LG

**Comment by blogbasti** [comment]
@lushsounds so sollte es nun passen, oder?

**Comment by lushsounds** [comment]
Ja perfekt, danke
