### ISSUE TITLE
Elemente im Footer auf iPhone in voller Breite

### ISSUE THREAD

**Issue by blogbasti** [blogbasti/klangturm#6]
Im footer auf den iPhone müssen die columns auf voller breite angezeigt werden.

**Comment by lushsounds** [comment]
![IMG_3612](https://user-images.githubusercontent.com/35580378/119237698-6ca43780-bb3e-11eb-9766-dde689ee4632.PNG)
![Bildschirmfoto 2021-05-22 um 20 41 59](https://user-images.githubusercontent.com/35580378/119237656-35358b00-bb3e-11eb-82e0-a47c20bd6c24.png)
Auf meine iMac überlappen sich im Footer die 3 Elemente (E-Mail-Adresse, Instagram-Link, Postadresse).
Die stehen alle nebeneinander. 
Auf meinem iPhone stehen die 3 Elemente unteinander. Jedes Element hat aber in sich einen Zeilenumbruch, obwohl der Text auf eine Zeile passen würde.

**Comment by lushsounds** [comment]
OK auf dem iMac sieht passt es jetzt mit dem Footer.
![Bildschirmfoto 2021-05-22 um 20 51 13](https://user-images.githubusercontent.com/35580378/119237875-79755b00-bb3f-11eb-9193-7a08af68ebe5.png)
