### ISSUE TITLE
Künstlerliste

### ISSUE THREAD

**Issue by lushsounds** [blogbasti/klangturm#7]
Sebastian, ich würde auf der Seite der Künstlerliste doch lieber links die Namen und rechts die Monate haben, weil:
Auf dem iPhone bricht die Zeile um, d.h. Vorname und Nachname sind auf 2 Zeilen verteilt.
Auch auf meinem iMac bricht die lange Zeile "Kinder der Schule auf der Veddel" um.
Mein Vorschlag: Wir lassen den Textblock "Künstler / Artist ..." einfach weg. Im Prinzip ist es ja selbsterklärend.
Auf dem Plakat für die Kirche, von dem wir das haben, finde ich das sinnvoll, weil da darauf hingewiesen wird, dass es die Künstler*innen für die Periode 2021/2022 sind. Ich habe vor, das Projekt im nächsten Jahr mit einem weiteren Set an Künstlern fortzusetzen.

**Comment by blogbasti** [comment]
Das "Plakat" auf der Website ist noch nicht fertig. Ich habe das Ziel, das Plakat auf der Startseite nachzubilden, damit wir einen Wiedererkennungseffekt zwischen Plakat und Website haben.

Es wäre auch kein Problem auf den jeweiligen Endgeräten die Namen der Artists einfach etwas kleiner darzustellen und so besser lesbar zu machen.

Ich würde vorschlagen, ich baue das Plakat zuende und wir bewerten danach neu.

**Comment by lushsounds** [comment]
Ja ok.
