### ISSUE TITLE
Titel im Footer

### ISSUE THREAD

**Issue by lushsounds** [blogbasti/klangturm#9]
Sebastian, im Footer steht 2 x der Titel.
Ich nehme an, dass der eigentliche Titel in der obersten Footer-Zeile der Titel aus der Titel aus der config.yml-Datei ist.
Aber wo kommt derselbe Titel darunter her? Dort würde ich "Kontakt:", "E-Mail"  oder löschen vorschlagen.
Danke und liebe Grüße
Benjamin

**Comment by blogbasti** [comment]
Der zweite Titel ist die Beschriftung der Email Adresse. Die kann ich gern ändern. Guter Punkt!
